name: flutter_paper_trail
description: A flutter plugin for PaperTrail logging service
version: 0.0.6
authors:
 - Alex Queudot <alexq@levinriegner.com>
homepage: https://github.com/levin-riegner/flutter_paper_trail

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.metaflow.flutterpapertrail
    pluginClass: FlutterPaperTrailPlugin

